### PR TITLE
Support null-safety

### PR DESCRIPTION
**Pull request by jhoogstraat**
This PR contains the necessary changes to support null safety. Moreover some optimizations are applied.

### CODE REVIEW

**Comment by vinicioslc** [comment]
Hi ! Thanks for your contribution!

I will check and approve in next 1 hours.

**Comment by jhoogstraat** [comment]
Ty for merging that fast! Maybe you should bump the version number, because there are breaking changes in there.
Oh and while we are there, `classifyGTIN` must not return an optional, because there are appropriate errors thrown instead.

**Comment by vinicioslc** [comment]
THANK YOU SO MUCH!
I'm sorry that this project has been out of action for 1 year, and the machine that I'm currently working on does not have a Flutter sdk.
I will deploy to the pub.dev registry this Saturday as soon as possible, and well observed on `classifyGTIN` i had not reflected on.

**Comment by jhoogstraat** [comment]
Do you mind pushing a new version to pub?
So I can point to that instead of a git repo?

**Comment by vinicioslc** [comment]
@jhoogstraat 
I'm sorry, I had some problems deploying due to having a new machine, and the task ended up being forgotten, due to other projects, I will configure my machine to deploy and launch it as soon as possible i'm doing right now

**Comment by vinicioslc** [comment]
@jhoogstraat your contribution has been released man, thanks a lot !!

**Pull request merged**
